FROM python:3.13-slim

WORKDIR /app

# Dependencias
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Artefacto compilado
COPY dist/transformapi-pyc.zip .

# Descomprimir aplicación compilada
RUN apt-get update \
    && apt-get install -y unzip \
    && unzip transformapi-pyc.zip \
    && rm transformapi-pyc.zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
