
DROP TABLE FITUSRLIB.TRALPR
DROP TABLE FITUSRLIB.TRALPE

CREATE TABLE FITUSRLIB.TRALPE(
	UUID VARCHAR(36) NOT NULL,
	PET_USUARIO CLOB NOT NULL,
	RES_API CLOB NOT NULL,
	FECHA_RESPUESTA TIMESTAMP NOT NULL,
	FECHA_PETICION TIMESTAMP NOT NULL
);

CREATE TABLE FITUSRLIB.TRALPR(
	UUID VARCHAR(36) NOT NULL,
	FECHA TIMESTAMP NOT NULL,
	TIPO_LOG VARCHAR(20) NOT NULL,
	MENSAJE VARCHAR(1500) NOT NULL,
	USUARIO VARCHAR(50) NOT NULL,
    METODO VARCHAR(100) NOT NULL,
	CLASE VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(15) NOT NULL
);

ALTER TABLE FITUSRLIB.TRALPR 
ALTER COLUMN FECHA
SET DEFAULT CURRENT TIMESTAMP;